---
- hosts: all
  become: yes
  gather_facts: no
  tasks:

  - name: Set authorized key for cluster to 'cluster'
    authorized_key:
      user: cluster
      state: present
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDKj/i9ARjxhdmDWWANgeIUFzAxK8jagct172rq78zY8rXfkz+6of+fmE9pUgYii/xTcuu4RSHhG8edf6Dv712Lt6jq5ItY1cI/CdXKAl4rmQ7P+1DVs+CCr2IkrNlFva4llIAb0gbG+XEv5N8cXOiZa+SJcsfhnacNFbESwW4RU5Km4v1gYIO+1UWKM3Gj5bqMeYpvtkJEJtnCGYrO+OjdmSm3YvPwbfKIZGrbnbN+U88TRVezxWlAXR6C4Ur/qwVL1XZZOxBHlSQbxb+tVdnGzHB+bZOz2cooXg6qyORlk2nyWi62V5SNpSKKRavGZgDA2hWSRXxVcD0PyXxnAmTh cluster@cluster000"
