---
- hosts: all
  become: yes
  tasks:

#Abraham 2020

  - name: Add user 'gene'
    user:
      name: gene
      password: "$6$9BaHMJB5xbuBBTsU$ii0GPiw80SoUBzz2vr3mzY/3lEO9gEdSq7j3s9pgOP8kD3FTr7SlTQuLjH8jiNFHWgbLpnpums7YiWD1nn14B0"
      shell: /bin/bash
      create_home: yes
      append: yes
      state: present
      groups: sudo

  - name: Allow 'sudo' group to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%sudo'
      line: '%sudo ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'

  - name: Set authorized key for Gene to 'gene'
    authorized_key:
      user: gene
      state: present
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCzG55yhLNiLl9+OhtQf8hij/FiWZZhcdqm97ZAJbxfML+KN/eHUqmwOTPDlGwOmDuy6Io9gybv5mnW8EBQOLMv+AMPwMGqJQIGdHzqSBdJFRmGO+v8W8VPkWZOcsWy34SKfYtAXp7cGvLCv/xlAAIYOT63Al/XZo0yeJRIJPw62Gr9j1qyFGZr/2A5PcA6cYFxIzpdJpube0KrllJ6mASZCzGkhNpv+PeKlwQBbTv4/TbU8hD32aUbe2h/7tOO9ICcoGYK9OqmHQ1iAmLAmIxIS7Ww+w13h1L/fDYoPkr48/zGuGTnzcLaYJWTlzo+ZHjh5zIPvy77Nl0y1ak85rmZ gene@Genes-MacBook-Pro.local"
