---
- hosts: bootstrap
  become: yes
  gather_facts: no
  roles:
  - { role: bootstrap }

- hosts: selflove
  become: yes
  gather_facts: no
  roles:
  - { role: wireguard_pre_install }
  - { role: install_wireguard }
  - { role: remove_pi }
  - { role: requirements }
  - { role: services }