---
- hosts: all
  become: yes
  gather_facts: no

  roles:
  - { role: packet2audio_install }
  - { role: packet2audio_systemd_setup }

  tasks:
  - name: Modify rc.local to set sound output to 100%
    lineinfile:
      path: /etc/rc.local
      line: "amixer cset numid=1 400"
      insertbefore: '^exit 0'