---
- hosts: pis
  gather_facts: no
  become: yes
  vars:
    home_dir: "/home/portal"
    oF_dir: "{{ home_dir }}/openFrameworks"
  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade packages
      apt:
        upgrade: full

    - name: Clean and remove packages
      apt:
        autoclean: yes
        autoremove: yes

#downloaded source into ./files
#wget https://openframeworks.cc/versions/v0.11.0/of_v0.11.0_linuxarmv6l_release.tar.gz

    - name: Upload openFrameworks
      copy:
        src: "of_v0.11.0_linuxarmv6l_release.tar.gz"
        dest: "{{ home_dir }}"

    - name: Create /home/portal/openFrameworks/
      file:
        path: "{{ oF_dir }}"
        state: directory

    - name: Unarchive of_v0.11.0_linuxarmv6l_release.tar.gz
      command:
        chdir: "{{ home_dir }}"
        cmd: "tar vxfz of_v0.11.0_linuxarmv6l_release.tar.gz -C openFrameworks --strip-components 1"

#cd /home/pi/openFrameworks/scripts/linux/debian
#sudo ./install_dependencies.sh

    # - name: install dependencies
    #   command:
    #     chdir: "{{oF_dir}}/scripts/linux/debian/"
    #     cmd: "sh install_dependencies.sh"

    - name: install dependencies
      script:
        cmd: "install_dependencies.sh"

#make Release -C /home/pi/openFrameworks/libs/openFrameworksCompiled/project

    - name: compile openFrameworks
      command:
        cmd: "make Release -C {{ oF_dir }}/libs/openFrameworksCompiled/project"

### OPTIONAL ###

# cd /home/pi/openFrameworks/examples/graphics/polygonExample
# make
# make run

    # - name: Compile an example
    #   make:
    #     chdir: "{{ oF_dir }}/examples/graphics/polygonExample"
