---
# from https://raspberrypi.stackexchange.com/questions/109452/wireguard-installation/109521#109521
# NOTE: This assumes a clean install. If you have previous versions of wireguard installed, purge them.
# run: `sudo apt-get purge wireguard wireguard-dkms dkms wireguard-tools`

- name: Check Wireguard Installation
  shell:
    cmd: wg
  ignore_errors: yes
  register: result

- name: Install Wireguard
  block:
    - name: Download Wireguard signing keys
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: "{{ item }}"
        state: present
      with_items:
        - 04EE7237B7D453EC
        - 648ACFD622F3D138

# echo 'deb http://httpredir.debian.org/debian buster-backports main contrib non-free' | sudo tee -a /etc/apt/sources.list.d/debian-backports.list

    - name: Add buster-backports main contrib non-free to apt source list
      lineinfile:
        path: /etc/apt/sources.list.d/debian-backports.list
        line: 'deb http://httpredir.debian.org/debian buster-backports main contrib non-free'
        state: present
        create: yes

    - name: Update installed packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install required packages
      apt:
        update_cache: no
        pkg:
        - raspberrypi-kernel-headers

    - name: Install Wireguard
      apt:
        update_cache: yes
        pkg:
        - wireguard-dkms
        - wireguard

    - name: Reboot!
      reboot:

  when: result.rc != 0