---
# Install Wireguard for PI (ref: https://github.com/adrianmihalko/raspberrypiwireguard)

- name: Check Wireguard Installation
  shell:
    cmd: wg
  register: result

- name: wg result
  debug:
    var: result.rc

- name: Install Wireguard
  block:
    - name: Download Wireguard signing keys
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: "{{ item }}"
        state: present
      with_items:
        - 8B48AD6246925553
        - 7638D0442B90D010
        - 04EE7237B7D453EC

    - name: Update installed packages
      apt:
        update_cache: yes
        upgrade: full
        autoremove: yes
        autoclean: yes
        force: yes

    - name: Install required packages
      apt:
        update_cache: no
        pkg:
        - raspberrypi-kernel-headers

    - name: Add unstable main to apt source list
      lineinfile:
        path: /etc/apt/sources.list.d/unstable.list
        line: 'deb http://deb.debian.org/debian/ unstable main'
        state: present
        create: yes

    - name: Install dirmngr
      apt:
        update_cache: no
        name: dirmngr

    - name: modify /etc/apt/preferences.d/limit-unstable
      blockinfile:
        path: /etc/apt/preferences.d/limit-unstable
        block: |
          Package: *
          Pin: release a=unstable
          Pin-Priority: 90
        create: yes

    - name: Install Wireguard
      apt:
        update_cache: yes
        name: wireguard

  when: result.rc != 0